main: me.sillysock.SillyCore.SillyCore
version: 1.0
api-version: 1.17
name: SillyCore
author: Sillysockk

commands:
  dev:
    description: Developer Commands.
  staff:
    description: Staff GUI.
  vanish:
    description: dude.
  memberlist:
    description: Lists all players online.
  nick:
    description: test
  realname:
    description: balls
  server:
    description: Manage the server.
  feed:
    description: Feed yourself or another player.
  heal:
    description: Heal yourself or another player.
  fly:
    description: Toggle flight for yourself or another player.