main: me.sillysock.SillyCore.SillyCore
version: 1.0-DeveloperBeta
api-version: 1.17
name: SillyCore
author: Sillysockk

commands:
  kick:
    description: Punish players by removing them from the server.
  dev:
    description: Developer Commands.
  staff:
    description: Staff GUI.
  vanish:
    description: dude.
  memberlist:
    description: Lists all players online.
  nick:
    description: test
  realname:
    description: balls
  server:
    description: Manage the server.
  feed:
    description: Feed yourself or another player.
  heal:
    description: Heal yourself or another player.
  fly:
    description: Toggle flight for yourself or another player.
  teleport:
    description: Teleport you, or another player to someone.
    aliases: [tp]
  tpstest:
    description: Unless you're silisoc don't run this.
  # Punishment
  ban:
    description: Remove a player from the server.
  mute:
    description: Revoke a players rights to speech.
  invview:
    description: Inventory View